# Assessed Problem #2

$$The \space system \space of \space linear \space equations \space that \space describes \space Kirchoff's \space laws \space for \space each \space of \space the \space current \space loops \space is:$$

$$i_1: +80i_1 -  50i_2 - 30i_3 -   0i_4 =  240$$
$$i_2: -50i_1 + 100i_2 - 10i_3 -  25i_4 = 0  $$
$$i_3: -30i_1 -  10i_2 + 65i_3 -  20i_4 = 0  $$
$$i_4: + 0i_1 -  25i_2 - 20i_3 + 100i_4 = 0  $$
$$$$
$$
This \space can \space be \space rewritten \space as \space a \space matrix \space calculation \space 'Ax = b'$$ $$$$

$$
\begin{bmatrix}
     80  & -50 & -30  &   0\\
    -50  & 100 & -10  & -25\\
    -30  & -10 &  65  & -20\\
      0  & -25 & -20  & 100\\
\end{bmatrix}
\space
\begin{bmatrix}
    i_1\\
    i_2\\
    i_3\\
    i_4\\
\end{bmatrix}
\space =\space
\begin{bmatrix}
    240\\
      0\\
      0\\
      0\\
\end{bmatrix}
$$

In [24]:
#Libraries
from scipy import linalg
from gaussPivot import *
#

#Define Matrix equation
A = [[80.,-50.,-30.,0.],
     [-50.,100.,-10.,-25.],
     [-30.,-10.,65.,-20.],
     [0.,-25.,-20.,100.]]
b = [240.,0.,0.,0.]
#

#Convert to triangular matrices
p,l,u = linalg.lu(A)
#

#Solve using Scipy
X1 =linalg.solve(A,b)
#

#Reformat the parameters for gaussPivot function
A = np.array(A)
b = np.array(b)
#

#Solve using Gaussian Elimination
X2 = gaussPivot(A,b)
#

#Outputs
print("Lower Triangular Matrix: \n")
print(str(l))
print("\n\n")
print("Upper Triangular Matrix: \n")
print(str(u))
print("\n\n")
print("Scipy Solution:")
print(X1)
print("\n\n")
print("Gaussian Elimination Solution:")
print(X2)
#

Lower Triangular Matrix: 

[[ 1.          0.          0.          0.        ]
 [-0.625       1.          0.          0.        ]
 [-0.375      -0.41818182  1.          0.        ]
 [ 0.         -0.36363636 -0.72984749  1.        ]]



Upper Triangular Matrix: 

[[ 80.         -50.         -30.           0.        ]
 [  0.          68.75       -28.75       -25.        ]
 [  0.           0.          41.72727273 -30.45454545]
 [  0.           0.           0.          68.68191721]]



Scipy Solution:
[ 8.36478985  5.32910389  5.42426646  2.41712926]



Gaussian Elimination Solution:
[ 8.36478985  5.32910389  5.42426646  2.41712926]


$Here \ you \ can \ see \ the \ Linalg \ function \ has \ computed \ the \ solution \ to \ the \ both \ of \ the \ Triangular \ matrices \ from \ the \ Kirchoff \ Equations \ also \ notice \\ that \ using \ GaussPivot \ and \ LinalgSolve \ have \ given \ two \ identical \ matrices \ as \ outputs \ It \ appears \ that \ the \ GaussPivot \ algorithm \ only \ returns \ the \\ matrix \ with \ integer \ parameters \ if \ you \ feed \ it \ integer \ matrices \ as \ a \ result \ all \ of \ the \ matrices \ have \ been \ defined \ in \ terms \ of \ floating \ point \ values$