# Gauss Elimination

In [1]:
## module gaussElimin
''' x = gaussElimin(a,b).
    Solves [a]{x} = {b} by Gauss elimination.
'''
from numpy import dot

def gaussElimin(a,b):
    n = len(b)
  # Elimination Phase
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               b[i] = b[i] - lam*b[k]
#               print a,b
  # Back substitution
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - dot(a[k,k+1:n],b[k+1:n]))/a[k,k]  # Put the solution back into the vector 'b'
    return b

# How do we use this code?

In [2]:
import numpy as np
from gaussElimin import *  # First, import the needed modules (numpy and above module - 
                           # which needs to be in the folder you are currently working in!!)

In [3]:
pwd   # This is how we find which folder we are currently using

u'/home/iti20/teaching/Intro_Sci_Comp/lectures/notebooks'

In [4]:
a = np.array([[1.,2.,3.], [4.,5.,6.],[7.,8.,2.]])  # Set up left hand side (matrix of variable coefficients)
b = np.array([6.,15.,17.])                   # Set up right hand side of the system of linear equations 

In [5]:
gaussElimin(a,b) # Call the solver

array([ 1.,  1.,  1.])

In [6]:
print('solution ',b)  # solutions for the three variables are now in the vector b! (also reported above)

('solution ', array([ 1.,  1.,  1.]))


# linalg.solve example

In [7]:
import scipy
from scipy import linalg
a = np.array([[1,2,3], [4,5,6],[7,8,2]])  # Set up left hand side (matrix of variable coefficients)
b = np.array([6,15,17])                   # Set up right hand side of the system of linear equations
linalg.solve(a,b)

array([ 1.,  1.,  1.])

# LU decomposition example

In [8]:
a = np.array([[1,2,3], [4,5,6],[7,8,2]])  # Set up matrix

In [9]:
import scipy
from scipy import linalg
P,L,U=linalg.lu(a)

In [10]:
print('P=',P)
print('L=',L)
print('U=',U)

('P=', array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]]))
('L=', array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]]))
('U=', array([[ 7.        ,  8.        ,  2.        ],
       [ 0.        ,  0.85714286,  2.71428571],
       [ 0.        ,  0.        ,  3.5       ]]))


# Tridiagonal solver example

In [7]:
import numpy as np
import scipy
from scipy import linalg    
tridiagonal = np.array([[1.,2.,0.], [4.,5.,6.],[0.,8.,2.]])  # Set up matrix

In [8]:
print(tridiagonal)

[[ 1.  2.  0.]
 [ 4.  5.  6.]
 [ 0.  8.  2.]]


In [9]:
diagonals = np.array([[0.,2.,6.], [1.,5.,2.],[4.,8.,0.]])  
# Set up matrix of containing the diagnonals

In [14]:
b = np.array([3.,15.,13.]) # set up the right-hand side of the equations

In [15]:
scipy.linalg.solve_banded((1,1), diagonals, b) # call the banded solver -> returns solution

array([ 0.33333333,  1.33333333,  1.16666667])

# Example of Gaussian elimination with pivoting 

In [17]:
import numpy as np
from gaussPivot import *  # First, import the needed modules 

In [19]:
a = np.array([[7.,-7.,1.], [-4.,4.,1.],[7.,7.,-4.]])  # Set up left hand side (matrix)
b = np.array([1.,1.,10.])                             # Set up right hand side 
gaussPivot(a,b)                                       # Call the solver

array([ 1.,  1.,  1.])